#!/bin/bash
#export NET_STATUS="--offline"
export NET_STATUS=""
#export LOGGER="-I customLogger.init.gradle"
export LOGGER=""

printf "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"

printf "\nCompile common...-----------------------------------------------------------------------\n"
#cd $COMMON_DEV_PATH/
gradle $NET_STATUS $LOGGER build $*
